create_clock -name clk -period 100 -waveform {0 50.00} [get_ports clk] 
set_input_delay -clock clk  20 -network_latency_included [all_inputs]
set_output_delay -clock clk 20 -network_latency_included [all_outputs]
set_clock_uncertainty -setup 0.1 [get_clocks clk] 
set_clock_uncertainty -hold 0.04 [get_clocks clk]
set_clock_transition 1.00 [get_clocks clk]
set_load -max 0.5 [all_outputs]
set_load -min 0.05 [all_outputs]
set_driving_cell -lib_cell BUFX2 -max [all_inputs]
set_driving_cell -lib_cell BUFX16 -min [all_inputs]
#set_driving_cell -lib_cell BUFX4 -max [get_ports hold]
